//ESTA LINEA IMPRIME EN CONSOLA
console.log("HOLA ADSI 181");
//ESTA LINEA PIDE UN NOMBRE Y LA GUARDA
let nombre= prompt("INGRESE NOMBRE");
//ESTA LINEA IMPRIME LA VARIABLE ALMACENADA
console.log(nombre);

