//SE USA LA PALABRA RESERVADA IF SEGUIDA DE PARÉNTESIS, DENTRO DE ESTOS VA LA CONDICIÓN . SI LA CONDICIÓN ES VERDADERA SE ENTRA AL BLOQUE DE CONDICIONAL EL CUAL VA ENTRE LLAVES,SI NO ES VERDADERA NO OCURRE NADA MÁS AL SER UN CONDICINAL SIMPLE.LA CONDICION SIEMPRE DEVUELVE UN BULEANO 
console.log('CONDICIONAL-SIMPLE')
let peso = 50 ;
let producto = 4 * 12 ;
if (peso < 54 && producto == 48 ){
  console.log ("Usted pesa menos de 54 kg");
};
//LOS DATOS PRIMITIVOS DEL LENGUAJE SIEMPRE SON CIERTOS 
if (1){
  console.log("Uno es cierto");
};
